// Playground - noun: a place where people can play

import Cocoa

var str = "Hello, playground"

println("Hello World")

// variables are 'mutable'...
var poplin: String = "My last name..."
poplin = "My father's last name..."

// constants are 'immutable'...
let ryan: String = "Family's last name..."
// error...
// ryan = "..."

// enum, struct, or class == data structure types...
// enum's and struct's are passed around by value...
// in other words, it's value is copied...
// classes are passed by reference...
// changes made to a class will affect the org. class...

